"""initial

Revision ID: 0b5143e2d794
Revises: 
Create Date: 2025-03-20 12:06:42.544702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0b5143e2d794'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('identifier', sa.String(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('createdAt', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identifier')
    )
    op.create_table('threads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('createdAt', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('userId', sa.UUID(), nullable=True),
    sa.Column('userIdentifier', sa.String(), nullable=True),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('elements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('threadId', sa.UUID(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('chainlitKey', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('display', sa.String(), nullable=True),
    sa.Column('objectKey', sa.String(), nullable=True),
    sa.Column('size', sa.String(), nullable=True),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('forId', sa.UUID(), nullable=True),
    sa.Column('mime', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['threadId'], ['threads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feedbacks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('forId', sa.UUID(), nullable=False),
    sa.Column('threadId', sa.UUID(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['threadId'], ['threads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('steps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('threadId', sa.UUID(), nullable=False),
    sa.Column('parentId', sa.UUID(), nullable=True),
    sa.Column('streaming', sa.Boolean(), nullable=False),
    sa.Column('waitForAnswer', sa.Boolean(), nullable=True),
    sa.Column('isError', sa.Boolean(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('input', sa.Text(), nullable=True),
    sa.Column('output', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.String(), nullable=True),
    sa.Column('start', sa.String(), nullable=True),
    sa.Column('end', sa.String(), nullable=True),
    sa.Column('generation', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('showInput', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('indent', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['threadId'], ['threads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('steps')
    op.drop_table('feedbacks')
    op.drop_table('elements')
    op.drop_table('threads')
    op.drop_table('users')
    # ### end Alembic commands ###
