"""add-props-to-elements

Revision ID: 1339834ff5a4
Revises: 0b5143e2d794
Create Date: 2025-03-20 12:34:06.826854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1339834ff5a4'
down_revision: Union[str, None] = '0b5143e2d794'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('elements', sa.Column('props', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('elements', 'props')
    # ### end Alembic commands ###
