"""add-defaultOpen-to-steps

Revision ID: 46bcd210abb8
Revises: 1339834ff5a4
Create Date: 2025-03-20 12:49:35.494033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46bcd210abb8'
down_revision: Union[str, None] = '1339834ff5a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('steps', sa.Column('defaultOpen', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('steps', 'defaultOpen')
    # ### end Alembic commands ###
