"""drop-column-identifier

Revision ID: d09646601959
Revises: 9f423e978c81
Create Date: 2025-03-17 09:45:25.059965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd09646601959'
down_revision: Union[str, None] = '9f423e978c81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_identifier_key', 'users', type_='unique')
    op.drop_column('users', 'identifier')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('identifier', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint('users_identifier_key', 'users', ['identifier'])
    # ### end Alembic commands ###
