services:
  chainlit-app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_API_VERSION: "2025-02-01-preview"
      APP_DATABASE_HOST: "db"
      APP_DATABASE_USERNAME: "postgres"
      APP_DATABASE_PASSWORD: "password"
      APP_DATABASE_NAME: "chainlit"
      AZURE_OPENAI_ENDPOINT: "https://shuntagami.openai.azure.com/"
      AZURE_STORAGE_ACCOUNT: "devstoreaccount1"
      AZURE_STORAGE_KEY: "Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw=="
      BLOB_CONTAINER_NAME: "shuntagami-chainlit-app"
      CHAINLIT_AUTH_SECRET: "Z,KKQ9_xYuteGo:WBbfY:0JXfX^Q~oEZb-m,dp0z6rdvsM7v2YQd^HhsemxmRf.Q"
      TZ: "Asia/Tokyo"
    ports:
      - "8000:8000"
    volumes:
      - .:/workspace
    working_dir: /workspace
    depends_on:
      - db
      - azurite
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "chainlit"
      TZ: "Asia/Tokyo"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite:latest
    container_name: azurite
    restart: always
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    volumes:
      - ./azurite:/data
volumes:
  postgres_data:
