services:
  chainlit-app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_API_VERSION: "2025-02-01-preview"
      AZURE_OPENAI_ENDPOINT: "https://lecture-openai.openai.azure.com/"
      APP_DATABASE_HOST: "db"
      APP_DATABASE_USERNAME: "postgres"
      APP_DATABASE_PASSWORD: "postgres"
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chainlit
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
